### PR TITLE
page/jtanurdjaja/resources-frontend2

### LINKED ISSUE #6: Resource Page Flow
Create the frontend of the resource pages, Figma here:
https://www.figma.com/proto/j5xygYtD7uunBcSwXJp8kd/MVP-File?scaling=scale-down&page-id=115%3A4249&node-id=157%3A5554&starting-point-node-id=157%3A5554&show-proto-sidebar=1

image
image
image

### PR DESCRIPTION
**Pull request by jtanurdjaja**
### Tracking Info

Resolves #6 

### Changes

What changes did you make?

- In the folder pages, we added resources.dart which is the first page of the resource flow that contains different resource categories.
- In the folder pages, we added category_name.dart which is the second page of the flow that displays resources associated with the category selected on the first page.
- In the folder pages, we added resource_title.dart which is the third page of the flow when a resource on the second page is selected.
- In the folder widgets, we added category_square.dart, which is a basic and standard template for the category displays in resources.dart.
- In the folder widgets, we added resource_rect.dart, which is a basic and standard template for the resource displays in category_name.dart.
- In the folder widgets, we added search_bar.dart for the search bar template.

### Testing

How did you confirm your changes worked? 

- We run the flutter run command on the terminal and build the application. Then, we click on each of the categories to see if the page routes to the next one, category_names. Then, we try scrolling in the category_names to see all of the listed resources. Then, we click on each resource to see if it navigates to the last page.
- For each page, we also resize the screen to check that the containers and text adjust in size and does not overflow.

### Confirmation of Change 
resource_pg1
resource_pg2
category_pg

### CODE REVIEW

**Review by aworld1 — APPROVED** [review]
Made small changes to main to include const modifiers + widget location was misplaced, looks good!

**Review by 2s2e — COMMENTED** [review]
LGTM!

**Review by nishantbalaji — CHANGES_REQUESTED** [review]
Overall PR lgtm, but could use some more comments. Can you write some documentation in the code explaining purpose / function?

**Review by aworld1 — APPROVED** [review]
Good comments, thanks for the change!

**Review by nishantbalaji — APPROVED** [review]
lgtm 🚢

**Pull request merged**
